---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-class: vsphere-storageclass
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  containers:
    - name: web-server
      image: nginx
      volumeMounts:
        - name: test-pv
          mountPath: /var/lib/www
  volumes:
    - name: test-pv
      persistentVolumeClaim:
        claimName: pvc-test
        readOnly: false
